# Generated by Django 2.2.5 on 2019-09-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]
'''
    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
'''