# Generated by Django 2.2.4 on 2019-09-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190921_2214'),
    ]
'''
    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
'''